/*
    Autogenerated with the script https://github.com/palcalde/iOSFontHelper
    You can generate a new running the script in terminal like: ruby fontHelper.rb path_to_ttf_file path_to_save_generated_code
    
    Sample: ruby iOSFontHelper/fontHelper.rb ~/Projects/MyApp/Fonts/yourFont.ttf .
*/
 
#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, <<FONTNAME>>) {
<<UNICODES_ENUM>>
};

@interface NSString (<<FONTNAME>>)

/**
 @abstract Returns the character associated to the icon enum passed as argument 
 */
+ (NSString*)<<FONTNAME>>CharacterStringForEnum:(<<FONTNAME>>)value;
@end