/*
    Autogenerated with the script https://github.com/palcalde/iOSFontHelper
    You can generate a new version with: ruby fontHelper-objectivec.rb path_to_ttf_file path_to_save_generated_code
    
    Sample: ruby iOSFontHelper/fontHelper.rb ~/Projects/MyApp/Fonts/yourFont.ttf .
*/
 
#import "NSString+<<FONTNAME>>.h"

@implementation NSString (<<FONTNAME>>)

+ (NSString*)<<FONTNAME>>CharacterStringForEnum:(<<FONTNAME>>)value {
    return [NSString <<FONTNAME>>UnicodeStrings][value];
}

+ (NSArray *)<<FONTNAME>>UnicodeStrings {
    static NSArray *fontUnicodeStrings;
    
    static dispatch_once_t unicodeStringsOnceToken;
    dispatch_once(&unicodeStringsOnceToken, ^{
        fontUnicodeStrings = <<UNICODES_ARRAY>>
    });
    return fontUnicodeStrings;
}


@end