/*
    Autogenerated with the script https://github.com/palcalde/iOSFontHelper
    You can generate a new running the script in terminal like: 
    ruby iOSFontHelper/fontHelper-swift.rb ~/Projects/MyApp/Fonts/yourFont.ttf .
*/
 
#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, <<FONTNAME>>) {
<<UNICODES_ENUM>>
};

@interface NSString (<<FONTNAME>>)

/**
 @abstract Returns the character associated to the icon enum passed as argument 
 */
+ (NSString*)<<FONTNAME>>CharacterStringForEnum:(<<FONTNAME>>)value;
@end