/*
    Autogenerated with the script https://github.com/palcalde/iOSFontHelper
    You can generate a new running the script in terminal like: ruby fontHelper-swift path_to_ttf_file path_to_save_generated_code
    
    Sample: ruby iOSFontHelper/fontHelper-swift.rb ~/Projects/MyApp/Fonts/yourFont.ttf .
*/

import Foundation

public extension String {
    enum <<FONTNAME>>: NSInteger {
        <<UNICODES_ENUM>>
    }
    
    static func unicodesArray() -> [String] {
        return <<UNICODES_ARRAY>>
    }
    
    static func <<FONTNAME>>IconStringForEnum(value: <<FONTNAME>>) -> String {
        return self.unicodesArray()[value.rawValue] as String
    }
}

